name: Build & Publish on Github Registry

on:
  push:
    tags: [ '*' ]

jobs:
  push_github_registry:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build --no-cache . --tag ghcr.io/bilyboy785/apache-php:latest --tag ghcr.io/bilyboy785/apache-php:$(git describe --tags --abbrev=0)
        docker push ghcr.io/bilyboy785/apache-php:latest
        docker push ghcr.io/bilyboy785/apache-php:$(git describe --tags --abbrev=0)